version: '3.8'

services:
  facade-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: facade-service
    ports:
      - "8000:8000"
    environment:
      - ROCKET_ADDRESS=0.0.0.0

  logging-service-1:
    build:
      context: .
      dockerfile: Dockerfile
      target: logging-service
    ports:
      - "8001:8001"
    environment:
      - ROCKET_PORT=8001
      - ROCKET_ADDRESS=0.0.0.0
      - REDIS_URL=redis://redis-1:6379
      - RUST_LOG=info
    depends_on:
      - redis-1
  
  redis-1:
    image: redis
    ports:
      - "63791:6379"
  
  logging-service-2:
    build:
      context: .
      dockerfile: Dockerfile
      target: logging-service
    ports:
      - "8002:8001"
    environment:
      - ROCKET_PORT=8001
      - ROCKET_ADDRESS=0.0.0.0
      - REDIS_URL=redis://redis-2:6379
      - RUST_LOG=info
    depends_on:
      - redis-2
  
  redis-2:
    image: redis
    ports:
      - "63792:6379"
  
  logging-service-3:
    build:
      context: .
      dockerfile: Dockerfile
      target: logging-service
    ports:
      - "8003:8001"
    environment:
      - ROCKET_PORT=8001
      - ROCKET_ADDRESS=0.0.0.0
      - REDIS_URL=redis://redis-3:6379
      - RUST_LOG=info
    depends_on:
      - redis-3
  
  redis-3:
    image: redis
    ports:
      - "63793:6379"
  
  messages-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: messages-service
    ports:
      - "8004:8002"
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8002
